# conditional builds
if: (type = push AND branch = master) OR (type = pull_request AND NOT branch = master)
language: node_js
node_js:
  - "stable"
install: yarn install
script:
  - yarn test:unit --no-cache
  - bash scripts/prepare-gh-pages-deployment.sh
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: gh-pages-ci
  on:
    branch: master