# conditional builds
if: (type = push AND branch = master) OR type = pull_request
language: node_js
node_js:
  - "stable"
install: yarn install
script:
  - yarn test:unit --no-cache
  - bash scripts/prepare-gh-pages-deployment.sh
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN #the env. variable is set in travis-ci > https://travis-ci.com/github/FLOIP/flow-builder/settings
  local_dir: dist #the build output folder
  on:
    branch: master
