language: node_js
node_js:
  - "stable"
install: yarn install
script:
  - bash scripts/prepare-gh-pages-deployment.sh
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: gh-pages-ci
  on:
    branch: VMO-3601-github-pages-auto-rebuild