name: PullRequestCheck

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn

      - name: ESLint
        env:
          pullRequestId: ${{github.event.number}}
          token: ${{secrets.GITHUB_TOKEN}}
        run: |
          yarn eslint -f checkstyle -o eslint_report.xml 'src/**/*' --ext .js --ext .ts --ext .tsx --ignore-pattern '*.css' --ignore-pattern '*.json' --ignore-pattern '*.yml'
          yarn violation-comments-to-github-command-line -ot $token -ro FLOIP -rn flow-builder -prid $pullRequestId -comment-only-changed-content false -create-comment-with-all-single-file-comments true -create-single-file-comments true -show-debug-info -v "CHECKSTYLE" "." ".*/eslint_report.xml" ESLint
      - name: PostEslintToGthub
        env:
          pullRequestId: ${{github.event.number}}
          token: ${{secrets.GITHUB_TOKEN}}
        if: ${{failure()}}
        run: yarn violation-comments-to-github-command-line -ot $token -ro FLOIP -rn flow-builder -prid $pullRequestId -comment-only-changed-content false -create-comment-with-all-single-file-comments true -create-single-file-comments true -v "CHECKSTYLE" "." ".*/eslint_report.xml" ESLint
